name: AI Review

on:
  pull_request:
    types: [opened, ready_for_review]
  issue_comment:
    types: [created]

jobs:
  papaya-claude-review:
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request' && github.actor != 'dependabot[bot]' && (github.event.action == 'opened' || github.event.action == 'ready_for_review'))
    uses: papayaglobal/workflows/.github/workflows/ai-review.yaml@main
    secrets: inherit
    with:
      pr-number: ${{ github.event.pull_request.number }}
      ref: ${{ github.event.pull_request.head.ref }}
      repository: ${{ github.event.pull_request.head.repo.full_name }}
